name: supabase_schema_generator
description: "A code generator for supabase_schema to generate Supabase schema definitions."
version: 0.0.1
resolution: workspace
repository: https://github.com/pckimlong/supabase_schema_library
homepage: https://github.com/pckimlong/supabase_schema_library
issue_tracker: https://github.com/pckimlong/supabase_schema_library/issues

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  supabase_schema: ^0.0.1
  flutter:
    sdk: flutter
  recase: ^4.1.0
  lean_builder: ^0.1.2
  analyzer: ">=7.4.0 <9.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
